require "bryan.launch"
require "bryan.options"
require "bryan.keymaps"
require "bryan.autocmds"

spec "bryan.colorscheme"
spec "bryan.junk-drawer"
spec "bryan.bufdelete"
spec "bryan.which-key"
spec "bryan.blink"
spec "bryan.snacks"
spec "bryan.todo-comments"
spec "bryan.treesitter"
spec "bryan.typescript"
spec "bryan.lualine"
spec "bryan.conform"
spec "bryan.linting"
spec "bryan.trouble"
spec "bryan.neogit"
spec "bryan.claude"
spec "bryan.autopairs"
spec "bryan.noice"
spec "bryan.cloak"
spec "bryan.supermaven"

require "bryan.lsp"
require "bryan.lazy"
